version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*os.File).Close
